#!/usr/bin/env python3
"""Generate a standalone HTML report for DeepTutor from structured JSON input."""
import argparse, json, sys
from datetime import datetime
from html import escape
from pathlib import Path

_ZH = {
    "title": "DeepTutor 导师调查报告", "missing": "信息不足",
    "sections": ["导师锐评","多维度评分","领域宏观趋势","学生去向(天花板原则)",
        "红绿灯速查","PUA/毒性风险","退休与稳定性风险","基本信息","导师类型分类",
        "目标匹配度","教育与职业时间线","研究方向","发表成果分析","合作网络",
        "基金与项目","学术指标","院系背景","总结与下一步","数据来源"],
    "score_labels": {5:"强烈推荐",4:"推荐",3:"中性",2:"谨慎",1:"不推荐"},
    "deal_banner": "存在一票否决项 — 请务必重视以下问题",
    "k": {"composite":"综合评分","weight":"权重","score":"评分","evidence":"依据",
        "dimension":"维度","lifecycle":"生命周期","funding_trend":"经费趋势",
        "job_market":"就业市场","disruption_risk":"颠覆风险","impact":"对学生影响",
        "name":"姓名","period":"时间","degree":"学位","papers":"论文数",
        "current_pos":"当前职位","red_flags":"红旗警告","green_flags":"绿色信号",
        "severity":"严重性","email":"邮箱","phone":"电话","office":"办公室",
        "institution":"机构","department":"院系","contact":"联系方式","ids":"学术 ID",
        "total_pubs":"总发表","h_index":"H-指数","i10_index":"i10-指数","trend":"趋势",
        "top_papers":"代表论文","journal":"期刊","year":"年份","citations":"引用",
        "amount":"金额","status":"状态","project":"项目","coauthor":"合作者",
        "count":"合作次数","relationship":"关系","age_est":"年龄估计",
        "retire_eta":"退休倒计时","fund_expiry":"经费到期","succession":"接班人",
        "assessment":"评估","platform":"平台","snippet":"摘要","accessed":"访问日期",
        "source":"数据源","url":"链接","recommendation":"推荐结论",
        "persona":"人设与现实","hidden_risk":"隐藏风险","underrated":"被低估的优势",
        "prediction":"五年预测","alternatives":"替代选择"},
}
_EN = {
    "title": "DeepTutor Advisor Investigation Report", "missing": "Insufficient data",
    "sections": ["Sharp Critique","Multi-Dimensional Scoring","Field Macro Trend",
        "Student Trajectory","Red/Green Flag Check","PUA/Toxicity Risk",
        "Retirement & Stability","Basic Info","Advisor Type","Goal-Advisor Match",
        "Education & Career Timeline","Research Directions","Publication Analysis",
        "Co-Author Network","Funding & Grants","Academic Metrics","Department Context",
        "Summary & Next Steps","Data Sources"],
    "score_labels": {5:"Strongly Recommended",4:"Recommended",3:"Neutral",2:"Caution",1:"Not Recommended"},
    "deal_banner": "DEAL-BREAKER TRIGGERED — Pay close attention to the issues below",
    "k": {"composite":"Composite Score","weight":"Weight","score":"Score","evidence":"Evidence",
        "dimension":"Dimension","lifecycle":"Lifecycle","funding_trend":"Funding Trend",
        "job_market":"Job Market","disruption_risk":"Disruption Risk","impact":"Impact on Student",
        "name":"Name","period":"Period","degree":"Degree","papers":"Papers",
        "current_pos":"Current Position","red_flags":"Red Flags","green_flags":"Green Flags",
        "severity":"Severity","email":"Email","phone":"Phone","office":"Office",
        "institution":"Institution","department":"Department","contact":"Contact",
        "ids":"Academic IDs","total_pubs":"Total Publications","h_index":"H-Index",
        "i10_index":"i10-Index","trend":"Trend","top_papers":"Top Papers","journal":"Journal",
        "year":"Year","citations":"Citations","amount":"Amount","status":"Status",
        "project":"Project","coauthor":"Co-author","count":"Count","relationship":"Relationship",
        "age_est":"Est. Age","retire_eta":"Retirement ETA","fund_expiry":"Funding Expiry",
        "succession":"Succession Plan","assessment":"Assessment","platform":"Platform",
        "snippet":"Snippet","accessed":"Accessed","source":"Data Source","url":"URL",
        "recommendation":"Recommendation","persona":"Persona vs Reality",
        "hidden_risk":"Hidden Risk","underrated":"Underrated Strength",
        "prediction":"5-Year Prediction","alternatives":"Alternatives"},
}
LANGS = {"zh": _ZH, "en": _EN}
FOOTER = "Generated by DeepTutor v5 — Powered by Claude"

def _g(d, *keys, default=""):
    for k in keys:
        if isinstance(d, dict): d = d.get(k, default)
        else: return default
    return d if d is not None else default

def _e(t): return escape(str(t)) if t else ""

def _sc(s):
    if s >= 4: return "#16a34a"
    return "#d97706" if s >= 3 else "#dc2626"

def _sb(s):
    if s >= 4: return "#dcfce7"
    return "#fef3c7" if s >= 3 else "#fee2e2"

def _sl(s, L): return L["score_labels"].get(round(s), "")
def _k(L, key): return L["k"].get(key, key)
def _so(i, t): return f'<section id="sec-{i}" class="card"><h2>{_e(t)}</h2>\n'
def _sc2(): return "</section>\n"
def _miss(L): return f'<p class="muted">{L["missing"]}</p>'

def _r0(d, L):
    sc = d.get("sharp_critique", {})
    if not sc: return _so(0, L["sections"][0]) + _miss(L) + _sc2()
    s = sc.get("score", 0); h = _so(0, L["sections"][0])
    h += f'<div class="verdict" style="border-left:4px solid {_sc(s)};padding-left:16px">'
    h += f'<p class="big-quote">&ldquo;{_e(sc.get("one_sentence", L["missing"]))}&rdquo;</p>'
    h += f'<span class="badge" style="background:{_sb(s)};color:{_sc(s)}">{_sl(s,L)} ({s}/5)</span></div>'
    for key, lk in [("persona_vs_reality","persona"),("hidden_risk","hidden_risk"),
            ("underrated_strength","underrated"),("five_year_prediction","prediction"),("alternatives","alternatives")]:
        v = sc.get(key, "")
        if v: h += f'<div class="qa"><strong>{_k(L,lk)}:</strong> {_e(v)}</div>'
    dbs = sc.get("deal_breakers", [])
    if dbs:
        h += '<div class="deal-breakers"><strong>Deal Breakers:</strong><ul>'
        for x in dbs: h += f"<li>{_e(x)}</li>"
        h += "</ul></div>"
    rec = sc.get("recommendation", "")
    if rec: h += f'<p><strong>{_k(L,"recommendation")}:</strong> {_e(rec)}</p>'
    return h + _sc2()

def _r1(d, L):
    sc = d.get("scores", {}); dims = sc.get("dimensions", []); comp = sc.get("composite", 0)
    h = _so(1, L["sections"][1])
    h += f'<div class="composite"><div class="composite-score" style="background:linear-gradient(135deg,{_sc(comp)},#f59e0b)">'
    h += f'<span class="comp-num">{comp:.1f}</span><span class="comp-label">{_sl(comp,L)}</span></div>'
    h += f'<span class="comp-title">{_k(L,"composite")}</span></div>'
    if dims:
        h += '<table><thead><tr>'
        for c in [_k(L,"dimension"),_k(L,"weight"),_k(L,"score"),_k(L,"evidence")]: h += f"<th>{c}</th>"
        h += "</tr></thead><tbody>"
        for dm in dims:
            s = dm.get("score", 0); pct = min(s/5*100, 100)
            h += f'<tr><td>{_e(dm.get("name",""))}</td><td>{dm.get("weight","")}</td>'
            h += f'<td><div class="bar-wrap"><div class="bar" style="width:{pct}%;background:{_sc(s)}"></div></div>{s}</td>'
            h += f'<td class="ev">{_e(dm.get("evidence",""))}</td></tr>'
        h += "</tbody></table>"
    return h + _sc2()

def _r2(d, L):
    ft = d.get("field_trend", {})
    if not ft: return _so(2, L["sections"][2]) + _miss(L) + _sc2()
    h = _so(2, L["sections"][2])
    h += f'<div class="lifecycle"><span class="emoji">{ft.get("emoji","")}</span> <strong>{_k(L,"lifecycle")}:</strong> {_e(ft.get("lifecycle",ft.get("lifecycle_en","")))}</div>'
    for fk, lk in [("funding_trend","funding_trend"),("job_market","job_market"),("disruption_risk","disruption_risk"),("impact_on_student","impact")]:
        v = ft.get(fk, "")
        if v: h += f'<p><strong>{_k(L,lk)}:</strong> {_e(v)}</p>'
    return h + _sc2()

def _r3(d, L):
    sts = d.get("students", []); h = _so(3, L["sections"][3])
    if not sts: return h + _miss(L) + _sc2()
    h += "<table><thead><tr>"
    for c in [_k(L,"name"),_k(L,"period"),_k(L,"degree"),_k(L,"papers"),_k(L,"current_pos")]: h += f"<th>{c}</th>"
    h += "</tr></thead><tbody>"
    for s in sts:
        h += f'<tr><td>{_e(s.get("name",""))}</td><td>{_e(s.get("period",""))}</td><td>{_e(s.get("degree",""))}</td><td>{s.get("papers","")}</td><td>{_e(s.get("current_position",""))}</td></tr>'
    return h + "</tbody></table>" + _sc2()

def _r4(d, L):
    fl = d.get("flags", {}); reds = fl.get("red", []); greens = fl.get("green", [])
    h = _so(4, L["sections"][4]) + '<div class="flag-grid"><div class="flag-col red-col">'
    h += f'<h3>{_k(L,"red_flags")}</h3>'
    if reds:
        for f in reds:
            h += f'<div class="flag-item red-flag"><span class="badge red-badge">{_e(f.get("severity",""))}</span> <strong>{_e(f.get("flag",""))}</strong><p class="ev">{_e(f.get("evidence",""))}</p></div>'
    else: h += _miss(L)
    h += f'</div><div class="flag-col green-col"><h3>{_k(L,"green_flags")}</h3>'
    if greens:
        for f in greens: h += f'<div class="flag-item green-flag"><strong>{_e(f.get("flag",""))}</strong><p class="ev">{_e(f.get("evidence",""))}</p></div>'
    else: h += _miss(L)
    return h + "</div></div>" + _sc2()

def _r5(d, L):
    sr = d.get("social_reviews", {}); h = _so(5, L["sections"][5])
    sm = sr.get("summary", ""); sources = sr.get("sources", [])
    if sm: h += f"<p>{_e(sm)}</p>"
    if sources:
        h += "<ul>"
        for s in sources:
            u = s.get("url", "")
            lnk = f'<a href="{_e(u)}" target="_blank">{_e(s.get("platform",""))}</a>' if u else _e(s.get("platform",""))
            h += f'<li>{lnk}: {_e(s.get("snippet",""))}</li>'
        h += "</ul>"
    if not sm and not sources: h += _miss(L)
    return h + _sc2()

def _r6(d, L):
    rr = d.get("retirement_risk", {}); h = _so(6, L["sections"][6])
    if not rr: return h + _miss(L) + _sc2()
    rs = rr.get("score", 0)
    h += f'<span class="badge" style="background:{_sb(rs)};color:{_sc(rs)}">{_k(L,"score")}: {rs}/5</span>'
    for fk, lk in [("age_estimate","age_est"),("retirement_eta","retire_eta"),("funding_expiry","fund_expiry"),("succession_plan","succession")]:
        v = rr.get(fk, "")
        if v: h += f'<p><strong>{_k(L,lk)}:</strong> {_e(v)}</p>'
    a = rr.get("assessment", "")
    if a: h += f'<p><strong>{_k(L,"assessment")}:</strong> {_e(a)}</p>'
    return h + _sc2()

def _r7(d, L):
    p = d.get("professor", {}); h = _so(7, L["sections"][7])
    nm = p.get("name", p.get("name_en", "")); h += f'<h3>{_e(nm)}</h3>'
    ti, ins, dep = p.get("title",""), p.get("institution",""), p.get("department","")
    if ti or ins or dep: h += f'<p>{_e(ti)} &mdash; {_e(ins)} {_e(dep)}</p>'
    ct = p.get("contact", {})
    if ct:
        parts = [f'{_k(L,k)}: {_e(ct[k])}' for k in ("email","phone","office") if ct.get(k)]
        if parts: h += f'<p><strong>{_k(L,"contact")}:</strong> {" | ".join(parts)}</p>'
    ids = p.get("ids", {})
    if ids:
        parts = []
        for k, v in ids.items():
            if v:
                parts.append(f'{_e(k)}: <a href="{_e(v)}" target="_blank">{_e(v)}</a>' if str(v).startswith("http") else f"{_e(k)}: {_e(v)}")
        if parts: h += f'<p><strong>{_k(L,"ids")}:</strong> {" | ".join(parts)}</p>'
    return h + _sc2()

def _r8(d, L):
    at = d.get("advisor_type", {}); h = _so(8, L["sections"][8])
    if not at: return h + _miss(L) + _sc2()
    h += f'<span class="badge accent-badge">{_e(at.get("type",at.get("type_en","")))}</span>'
    ev = at.get("evidence", "")
    if ev: h += f'<p>{_e(ev)}</p>'
    return h + _sc2()

def _r9(d, L):
    gm = d.get("goal_match", {}); h = _so(9, L["sections"][9])
    if not gm: return h + _miss(L) + _sc2()
    for k, v in gm.items(): h += f'<p><strong>{_e(k)}:</strong> {_e(v)}</p>'
    return h + _sc2()

def _r10(d, L):
    items = []
    for x in d.get("education", []):
        items.append((x.get("period",""), f'{_e(x.get("degree",""))} — {_e(x.get("institution",""))} ({_e(x.get("field",""))})'))
    for x in d.get("career", []):
        items.append((x.get("period",""), f'{_e(x.get("position",""))} — {_e(x.get("institution",""))}'))
    h = _so(10, L["sections"][10])
    if not items: return h + _miss(L) + _sc2()
    h += '<div class="timeline">'
    for per, desc in sorted(items, key=lambda x: x[0]):
        h += f'<div class="tl-item"><span class="tl-period">{_e(per)}</span><span class="tl-desc">{desc}</span></div>'
    return h + "</div>" + _sc2()

def _r11(d, L):
    rd = d.get("research_directions", d.get("research", "")); h = _so(11, L["sections"][11])
    if not rd: return h + _miss(L) + _sc2()
    if isinstance(rd, list): h += "<ul>" + "".join(f"<li>{_e(r)}</li>" for r in rd) + "</ul>"
    else: h += f"<p>{_e(rd)}</p>"
    return h + _sc2()

def _r12(d, L):
    pub = d.get("publications", {}); h = _so(12, L["sections"][12])
    if not pub: return h + _miss(L) + _sc2()
    stats = [f'<strong>{_k(L,lk)}:</strong> {_e(pub[fk])}' for fk, lk in [("total","total_pubs"),("h_index","h_index"),("i10_index","i10_index"),("trend","trend")] if pub.get(fk)]
    if stats: h += "<p>" + " &nbsp;|&nbsp; ".join(stats) + "</p>"
    tp = pub.get("top_papers", [])
    if tp:
        h += f'<h4>{_k(L,"top_papers")}</h4><table><thead><tr><th>#</th><th>Title</th><th>{_k(L,"journal")}</th><th>{_k(L,"year")}</th><th>{_k(L,"citations")}</th></tr></thead><tbody>'
        for i, p in enumerate(tp, 1):
            h += f'<tr><td>{i}</td><td>{_e(p.get("title",""))}</td><td>{_e(p.get("journal",""))}</td><td>{p.get("year","")}</td><td>{p.get("citations","")}</td></tr>'
        h += "</tbody></table>"
    return h + _sc2()

def _r13(d, L):
    cas = d.get("coauthors", []); h = _so(13, L["sections"][13])
    if not cas: return h + _miss(L) + _sc2()
    h += f'<table><thead><tr><th>{_k(L,"coauthor")}</th><th>{_k(L,"count")}</th><th>{_k(L,"relationship")}</th><th>{_k(L,"institution")}</th></tr></thead><tbody>'
    for c in cas:
        h += f'<tr><td>{_e(c.get("name",""))}</td><td>{c.get("count","")}</td><td>{_e(c.get("relationship",""))}</td><td>{_e(c.get("institution",""))}</td></tr>'
    return h + "</tbody></table>" + _sc2()

def _r14(d, L):
    funds = d.get("funding", []); h = _so(14, L["sections"][14])
    if not funds: return h + _miss(L) + _sc2()
    h += f'<table><thead><tr><th>{_k(L,"project")}</th><th>{_k(L,"amount")}</th><th>{_k(L,"period")}</th><th>{_k(L,"status")}</th></tr></thead><tbody>'
    for f in funds:
        st = f.get("status", ""); bc = "green-badge" if st == "active" else "muted-badge"
        h += f'<tr><td>{_e(f.get("name",""))}</td><td>{_e(f.get("amount",""))}</td><td>{_e(f.get("period",""))}</td><td><span class="badge {bc}">{_e(st)}</span></td></tr>'
    return h + "</tbody></table>" + _sc2()

def _r15(d, L):
    pub = d.get("publications", {}); h = _so(15, L["sections"][15])
    if not pub: return h + _miss(L) + _sc2()
    h += f'<p><strong>{_k(L,"h_index")}:</strong> {pub.get("h_index",L["missing"])} &nbsp;|&nbsp; <strong>{_k(L,"i10_index")}:</strong> {pub.get("i10_index",L["missing"])}</p>'
    return h + _sc2()

def _r16(d, L):
    h = _so(16, L["sections"][16]); di = d.get("department_context", ""); p = d.get("professor", {})
    if di and isinstance(di, str): h += f"<p>{_e(di)}</p>"
    elif p.get("institution") or p.get("department"): h += f'<p>{_e(p.get("institution",""))} — {_e(p.get("department",""))}</p>'
    else: h += _miss(L)
    return h + _sc2()

def _r17(d, L):
    ns = d.get("next_steps", []); h = _so(17, L["sections"][17])
    if not ns: return h + _miss(L) + _sc2()
    h += "<ol>" + "".join(f"<li>{_e(s)}</li>" for s in ns) + "</ol>"
    return h + _sc2()

def _r18(d, L):
    ds = d.get("data_sources", []); h = _so(18, L["sections"][18])
    if not ds: return h + _miss(L) + _sc2()
    h += f'<table><thead><tr><th>{_k(L,"source")}</th><th>{_k(L,"url")}</th><th>{_k(L,"accessed")}</th></tr></thead><tbody>'
    for s in ds:
        u = s.get("url", ""); lnk = f'<a href="{_e(u)}" target="_blank">{_e(u)}</a>' if u else ""
        h += f'<tr><td>{_e(s.get("name",""))}</td><td>{lnk}</td><td>{_e(s.get("accessed",""))}</td></tr>'
    return h + "</tbody></table>" + _sc2()

CSS = """\
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#F9FAFB;color:#1f2937;line-height:1.6}
a{color:#d97706;text-decoration:none}a:hover{text-decoration:underline}
.layout{display:flex;min-height:100vh}
nav{position:fixed;top:0;left:0;width:240px;height:100vh;overflow-y:auto;background:#fff;border-right:1px solid #e5e7eb;padding:24px 16px;z-index:10}
nav .logo{font-weight:700;font-size:18px;color:#d97706;margin-bottom:20px}
nav a{display:block;padding:6px 10px;border-radius:6px;font-size:13px;color:#4b5563;margin-bottom:2px;transition:background .15s}
nav a:hover{background:#fef3c7;text-decoration:none}
main{margin-left:240px;padding:32px 40px;max-width:960px;width:100%}
.card{background:#fff;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,.08);padding:28px 32px;margin-bottom:24px}
.card h2{font-size:20px;color:#111827;border-bottom:2px solid #f3f4f6;padding-bottom:10px;margin-bottom:16px}
.badge{display:inline-block;padding:3px 12px;border-radius:20px;font-size:13px;font-weight:600}
.accent-badge{background:#fef3c7;color:#d97706}
.red-badge{background:#fee2e2;color:#dc2626}
.green-badge{background:#dcfce7;color:#16a34a}
.muted-badge{background:#f3f4f6;color:#6b7280}
.muted{color:#9ca3af;font-style:italic}
table{width:100%;border-collapse:collapse;margin-top:12px;font-size:14px}
th{background:#f9fafb;text-align:left;padding:10px 12px;font-weight:600;border-bottom:2px solid #e5e7eb}
td{padding:10px 12px;border-bottom:1px solid #f3f4f6}
.bar-wrap{display:inline-block;width:100px;height:10px;background:#f3f4f6;border-radius:5px;vertical-align:middle;margin-right:8px}
.bar{height:100%;border-radius:5px}
.composite{text-align:center;margin-bottom:20px}
.composite-score{display:inline-flex;flex-direction:column;align-items:center;justify-content:center;width:120px;height:120px;border-radius:50%;color:#fff}
.comp-num{font-size:36px;font-weight:800;line-height:1}
.comp-label{font-size:12px;margin-top:4px}
.comp-title{display:block;margin-top:8px;font-weight:600;color:#6b7280;font-size:14px}
.big-quote{font-size:20px;font-weight:600;margin-bottom:10px;color:#111827}
.qa{margin:10px 0;padding:8px 12px;background:#f9fafb;border-radius:8px;font-size:14px}
.deal-breakers ul{margin:8px 0 0 20px}
.flag-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}
.flag-col h3{margin-bottom:10px}
.flag-item{padding:10px 14px;border-radius:8px;margin-bottom:8px;font-size:14px}
.red-flag{background:#fef2f2;border-left:3px solid #dc2626}
.green-flag{background:#f0fdf4;border-left:3px solid #16a34a}
.ev{font-size:13px;color:#6b7280;margin-top:4px}
.verdict{margin-bottom:16px}
.lifecycle{font-size:18px;margin-bottom:12px}
.emoji{font-size:28px;vertical-align:middle}
.timeline{position:relative;padding-left:20px;border-left:3px solid #d97706}
.tl-item{margin-bottom:16px;position:relative}
.tl-item::before{content:'';position:absolute;left:-26px;top:6px;width:12px;height:12px;border-radius:50%;background:#d97706}
.tl-period{font-weight:600;color:#d97706;display:block;font-size:13px}
.tl-desc{font-size:14px}
.deal-banner{background:#dc2626;color:#fff;text-align:center;padding:14px;font-weight:700;font-size:16px;position:sticky;top:0;z-index:20}
footer{text-align:center;padding:24px;font-size:13px;color:#9ca3af}
h4{margin:16px 0 8px;font-size:15px}
@media(max-width:768px){nav{position:static;width:100%;height:auto;border-right:none;border-bottom:1px solid #e5e7eb;display:flex;flex-wrap:wrap;gap:4px;padding:12px}nav .logo{width:100%}nav a{font-size:12px;padding:4px 8px}main{margin-left:0;padding:16px}.flag-grid{grid-template-columns:1fr}}
@media print{nav,.deal-banner{display:none!important}main{margin-left:0}.card{box-shadow:none;break-inside:avoid}body{background:#fff}}"""

_RENDERERS = [_r0,_r1,_r2,_r3,_r4,_r5,_r6,_r7,_r8,_r9,_r10,_r11,_r12,_r13,_r14,_r15,_r16,_r17,_r18]

def generate_html(data: dict) -> str:
    lang = data.get("lang", "zh")
    L = LANGS.get(lang, _ZH)
    prof = data.get("professor", {})
    prof_name = prof.get("name", prof.get("name_en", ""))
    deal = _g(data, "sharp_critique", "deal_breaker_triggered", default=False)
    nav = "".join(f'<a href="#sec-{i}">{i+1}. {_e(s)}</a>\n' for i, s in enumerate(L["sections"]))
    body = "".join(r(data, L) for r in _RENDERERS)
    banner = f'<div class="deal-banner">{L["deal_banner"]}</div>' if deal else ""
    gen = data.get("generated_at", datetime.now().isoformat(timespec="seconds"))
    ver = data.get("version", "v5")
    return f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{_e(L["title"])} — {_e(prof_name)}</title>
<style>{CSS}</style>
</head>
<body>
{banner}
<div class="layout">
<nav>
  <div class="logo">DeepTutor</div>
  {nav}
</nav>
<main>
  <h1 style="margin-bottom:8px">{_e(L["title"])}</h1>
  <p style="color:#6b7280;margin-bottom:28px">{_e(prof_name)} &mdash; {_e(gen)}</p>
  {body}
  <footer>{FOOTER} ({ver})</footer>
</main>
</div>
</body>
</html>"""

def main():
    ap = argparse.ArgumentParser(description="Generate a DeepTutor HTML report from JSON.")
    ap.add_argument("input", help="Path to input JSON file")
    ap.add_argument("-o", "--output", help="Output HTML file (default: stdout)", default=None)
    args = ap.parse_args()
    with open(args.input, "r", encoding="utf-8") as f:
        data = json.load(f)
    html = generate_html(data)
    if args.output:
        Path(args.output).write_text(html, encoding="utf-8")
        print(f"Report written to {args.output}", file=sys.stderr)
    else:
        print(html)

if __name__ == "__main__":
    main()
